
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euipgahxptezlqdyehmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1aXBnYWh4cHRlemxxZHllaG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTA3NjYsImV4cCI6MjA1ODIyNjc2Nn0.52az1jnIhXbrN9PlzYs8JubXF2DMIlNi9gjv-Noz9fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Add type definition for our tables
export type SavedPDF = Database['public']['Tables']['saved_pdfs']['Row'];

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
